import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../../../../core/words/word_alphabet.dart';
import '../domain/spelling_bee_models.dart';
import '../domain/spelling_bee_word_index.dart';

/// Loads the word lists a language's puzzles are built from, once per session.
///
/// Three lists make up one [BeeWordIndex]: the two tier lists that the bars
/// are drawn from (`bee_normal.txt`, `bee_difficult.txt`, both generated by
/// `tool/generate_bee_wordlists.py`) and the full `all.txt` the language
/// already ships for Wordle, which decides what else is accepted at all.
///
/// Parsing runs in a background isolate — `all.txt` is a few hundred thousand
/// lines — and only words a hive could ever spell are kept: at least
/// [kBeeMinWordLength] letters, and no more than [kBeeLetterCount] different
/// ones. That throws away about half of the English list before it ever
/// reaches the UI isolate.
class SpellingBeeWordRepository {
  final Map<String, BeeWordIndex> _indexes = {};
  final Map<String, Future<BeeWordIndex>> _loading = {};

  Future<BeeWordIndex> index(String languageCode) {
    final cached = _indexes[languageCode];
    if (cached != null) return Future.value(cached);

    return _loading[languageCode] ??= _load(languageCode).then((index) {
      _indexes[languageCode] = index;
      _loading.remove(languageCode);
      return index;
    }, onError: (Object error) {
      _loading.remove(languageCode);
      throw error;
    });
  }

  Future<BeeWordIndex> _load(String languageCode) async {
    Future<String> read(String file) => rootBundle.loadString(
      'assets/wordlists/$languageCode/$file',
      cache: false,
    );

    final sources = await Future.wait([
      read('bee_normal.txt'),
      read('bee_difficult.txt'),
      read('all.txt'),
    ]);

    final parsed = await compute(
      _parseIndex,
      _ParseRequest(
        languageCode: languageCode,
        normal: sources[0],
        difficult: sources[1],
        accepted: sources[2],
      ),
    );

    return BeeWordIndex(
      languageCode: languageCode,
      normal: BeeWordSet(words: parsed.normal, masks: parsed.normalMasks),
      difficult: BeeWordSet(
        words: parsed.difficult,
        masks: parsed.difficultMasks,
      ),
      accepted: BeeWordSet(
        words: parsed.accepted,
        masks: parsed.acceptedMasks,
      ),
    );
  }
}

class _ParseRequest {
  const _ParseRequest({
    required this.languageCode,
    required this.normal,
    required this.difficult,
    required this.accepted,
  });

  final String languageCode;
  final String normal;
  final String difficult;
  final String accepted;
}

class _ParseResult {
  const _ParseResult({
    required this.normal,
    required this.normalMasks,
    required this.difficult,
    required this.difficultMasks,
    required this.accepted,
    required this.acceptedMasks,
  });

  final List<String> normal;
  final Uint32List normalMasks;
  final List<String> difficult;
  final Uint32List difficultMasks;
  final List<String> accepted;
  final Uint32List acceptedMasks;
}

/// Runs in a background isolate.
_ParseResult _parseIndex(_ParseRequest request) {
  final bits = <int, int>{};
  final alphabet = WordAlphabet.lettersFor(request.languageCode);
  for (var i = 0; i < alphabet.length; i++) {
    bits[alphabet.codeUnitAt(i)] = i;
  }

  (List<String>, Uint32List) parse(String content) {
    final words = <String>[];
    final masks = <int>[];
    final seen = <String>{};

    for (final line in const LineSplitter().convert(content)) {
      final word = WordAlphabet.normalizeWord(line, request.languageCode);
      if (word == null || word.length < kBeeMinWordLength) continue;
      final mask = beeLetterMask(word, bits);
      if (beeLetterCount(mask) > kBeeLetterCount) continue;
      if (!seen.add(word)) continue;
      words.add(word);
      masks.add(mask);
    }
    return (words, Uint32List.fromList(masks));
  }

  final (normal, normalMasks) = parse(request.normal);
  final (difficult, difficultMasks) = parse(request.difficult);
  final (accepted, acceptedMasks) = parse(request.accepted);

  return _ParseResult(
    normal: normal,
    normalMasks: normalMasks,
    difficult: difficult,
    difficultMasks: difficultMasks,
    accepted: accepted,
    acceptedMasks: acceptedMasks,
  );
}
